id: 2726b15bb0694a1cbeddef6fb5311141
initial_creation_type: ocr
source_metadata:
  volumes:
    81556eda7ad54cfbbb4f0b4a66aec793:
      base_file: v028.txt
      image_group_id: I1PD95873
      title: ''
      total_pages: 1445
      volume_number: 28
